### PR TITLE
Added pointer clamping to stop going past origin

### PR DESCRIPTION
**Pull request by Ella-0**
Stops pointer from going past 0,0 making it less difficult to lose. I would stop it from going past the screen dimensions but I don't know where I can get that information.

### CODE REVIEW

**Comment by st3r4g** [comment]
On my pc (with mouse) this incorrectly clamps the pointer to a diagonal... not sure why

**Comment by Ella-0** [comment]
I think that should fix it

**Comment by st3r4g** [comment]
Looks good now. Thanks! Screen dimensions would have to be taken from the `screen` object (see `screen_get_dimensions`)

**Comment by Ella-0** [comment]
I've been thinking about how best to communicate the pointer bounds to the input backend. I'm thinking probably through `input_setup`. This wouldn't work well with hot plug in the future but It should be fine until then.

**Pull request merged**
