### PR TITLE
Added bounds checking to stop going past remaining screen edges

### PR DESCRIPTION
**Pull request by Ella-0**
I think this should do it though

### CODE REVIEW

**Comment by st3r4g** [comment]
Hmm not really a fan of duplicating state like that. I think `input.c` needs to be refactored so that:

1. we get rid of the global `pointer`
2. we send coordinates of relative motion to `swvkc.c` via `input_events.motion`
3. we keep track of the pointer on-screen position and do the clamping in `swvkc.c` (inside `input_motion_notify`) where we get screen size by `screen_get_dimensions(server->screen)`

You could try that if you like, else I'll do it when I have time.

**Comment by Ella-0** [comment]
I have lots of time at the moment, at least until I go back to school but there's always uncertainty about that given the current climate. I'll try the things you said and see how it goes.

**Comment by Ella-0** [comment]
I don't quite understand what `motion_x` and `motion_y` do in `input.c`.

**Comment by st3r4g** [comment]
Looks good! But remove the old lines instead of commenting them. Also remove `pointer_bounds`, we don't need it now.
Could you squash the commits into a single one (with `git rebase -i`) and then force push the branch? History will be a bit cleaner this way.

> I don't quite understand what `motion_x` and `motion_y` do in `input.c`.

It is for the touchpad case, they are reset to false when you lift your finger (= finger slide motion has ended) so that the very next touch event is ignored (it would cause a sudden jump otherwise, because lift position != new touch position)

**Comment by Ella-0** [comment]
Okay thank you, and yeah that commit was very much WIP I'll remove the comments Just wanted to store the changes I made before asking a question. And yeah I will squash the commits.

**Comment by st3r4g** [comment]
Thanks!

**Pull request merged**
